Squashed 'ansible_roles/ansible_role_base/' changes from 2ef3ff1..57e79e7
57e79e7 feat: user password変更処理追加
1d5b367 ci: github actionsの設定変更
075a671 ci: pycrypto のビルドエラーに対処
27589f5 Merge commit 'f75213a3aa6c3e8c82eab8a9500e137e255bc1a3'
2603f96 ci: 冪等性向上のための変更
de8c0e4 Update README.md
c768bee Update README.md
194b655 Update base.yml
564e2b2 Update base.yml
5a42496 Update base.yml
db91cf4 Update base.yml
e10b66e Update base.yml
9fbe23f Update base.yml
618aa2a Update base.yml
551411a Update base.yml
a35ebfe Update base.yml
db2a9f6 ci: 冪等性向上のための変更

git-subtree-dir: ansible_roles/ansible_role_base
git-subtree-split: 57e79e7f38eb14a2d34daca722d2484f022eba15

diff --git a/.github/workflows/molecule-test.yml b/.github/workflows/molecule-test.yml
--- a/.github/workflows/molecule-test.yml
+++ b/.github/workflows/molecule-test.yml
@@ -1,5 +1,4 @@
 name: Molecule Test
-
 on:
   push:
     branches:
@@ -8,44 +7,72 @@ on:
   pull_request:
     branches:
       - main
+      - develop
 
 jobs:
-  test:
+  build:
     runs-on: ubuntu-latest
-
+    timeout-minutes: 120
     strategy:
+      max-parallel: 4
       matrix:
-        ansible-version: [2.9, 2.10, 2.11]
-        python-version: [3.8, 3.9, 3.10]
-        role: [ansible_role_base, ansible_role_shirasagi]
+        python-version: ["3.10", "3.11", "3.12"]
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
+      - uses: actions/checkout@v3 # 最新バージョンに更新
 
-      - name: Set up Python
-        uses: actions/setup-python@v2
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v4 # 最新バージョンに更新
         with:
           python-version: ${{ matrix.python-version }}
 
+      - name: Cache pip
+        uses: actions/cache@v3 # 最新バージョンに更新
+        with:
+          path: ~/.cache/pip
+          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+          restore-keys: ${{ runner.os }}-pip-
+
       - name: Install dependencies
         run: |
-          python -m pip install --upgrade pip
-          pip install ansible==${{ matrix.ansible-version }} molecule[docker] docker
+          python3 -m pip install --upgrade pip
+          python3 -m pip install -r requirements.txt  # 依存関係を一度にインストール
 
-      - name: Install role requirements
+      - name: Install required Ansible collections
         run: |
-          cd ansible_roles/${{ matrix.role }}
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+          ansible-galaxy collection install community.general
 
-      - name: Run Molecule test for ${{ matrix.role }}
+      - name: Test with molecule
         run: |
-          cd ansible_roles/${{ matrix.role }}
-          MOLECULE_DESTROY=never molecule test
+          molecule test  # ルートディレクトリで実行
 
-      - name: Upload Molecule Logs for ${{ matrix.role }}
-        if: always()
-        uses: actions/upload-artifact@v3
-        with:
-          name: molecule-logs-${{ matrix.role }}
-          path: ansible_roles/${{ matrix.role }}/.molecule
+      - name: Docker Cleanup
+        run: |
+          docker system prune -f --volumes  # 使っていないDockerリソースをクリーンアップ
+          docker network prune -f            # 不要なDockerネットワークを削除
+          docker container prune -f          # 停止したコンテナを削除
+          docker volume prune -f             # 未使用のボリュームを削除
+
+  #  release:
+  #    if: github.ref == 'refs/heads/main' # mainブランチの場合のみ実行
+  #    needs: build # buildジョブが成功した後に実行
+  #    runs-on: ubuntu-latest
+  #    steps:
+  #      - uses: actions/checkout@v3
+  #
+  #      - name: Ansible Galaxy release
+  #        id: galaxy_release
+  #        uses: robertdebock/galaxy-action@1.2.0
+  #        with:
+  #          galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
+  #          git_branch: ${{ github.ref_name }} # タグ名をブランチとして使用
+  #          github_user: ${{ secrets.MY_GITHUB_USERNAME }}
+  #          github_repo: ${{ github.repository }}
+  #          github_token: ${{ secrets.GALAXY_API_KEY2 }}
+  #
+  #      - name: Check for errors during Ansible Galaxy release
+  #        if: steps.galaxy_release.outcome == 'failure'
+  #        run: |
+  #          echo "Ansible Galaxy release failed. Please check the logs for details."
+  #          exit 1
+  #
